import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "@/ui/styles/globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import { Header } from "../ui/components/Header";

const publicSansHeading = Public_Sans({
  subsets:['latin'],
  variable:'--font-sans'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", publicSansHeading.variable, "font-sans")}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          <Header />
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
